# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      matrix:
        node-version: [14.x]

    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - run: python --version
      - run: npm install
      - run: npm run prepublish
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v3
      #   with:
      #     token: ${{ secrets.TOKEN_GITHUB_SECRET }}
      #     repository: OttawaSTEM/scratch-arduino-gui
      #     event-type: release_scratch_arduino_blocks
